import Link from "next/link";

export default function Page() {
  return (
    <section className="p-4 mt-28">
      <div className="container mx-auto px-4">
        <div className="border border-black p-8 md:p-12 bg-[#ffffffe0]">
          <h1 className="text-4xl text-center uppercase font-bold mb-8">
            Privacy Policy
          </h1>

          <ul className="privacy-content list-decimal">
            <li className="text-lg">
              <b>Introduction</b>

              <p>
                Welcome to Pledgecom <b>Labs</b>
              </p>

              <p>
                <strong>Pledgecom Labs</strong> ("us", "we", or "our") operates
                <Link href="/" className="text-blue-600 hover:text-blue-700">
                  {" "}
                  pledgecom.org{" "}
                </Link>{" "}
                and the
                <strong> Pledgecom app</strong> (hereinafter referred to as
                <b>"Service"</b>)
              </p>

              <p>
                Our Privacy Policy governs your visit to
                <Link href="/" className="text-blue-600 hover:text-blue-700">
                  {" "}
                  pledgecom.org{" "}
                </Link>
                , and use of the
                <strong> Pledgecom app</strong>, and explains how we collect,
                safeguard and disclose information that results form your use of
                our Service.
              </p>

              <p>
                We use your data to provide and improve Service. By using the
                Service, you agree to the collection and use of information per
                this policy. Unless otherwise defined in this Privacy Policy,
                the terms used in this Privacy Policy have the same meanings as
                in our Terms and Conditions.
              </p>

              <p>
                Our Terms and Conditions (<b>"Terms"</b>) govern all use of our
                Service and together with the Privacy Policy constitute your
                agreement with us (<b>"Agreement"</b>).
              </p>
            </li>

            <li>
              <b>Definitions</b>

              <p>
                <b>SERVICE</b> means the
                <a href="https://pledgecom.org/">pledgecom.org</a> website and
                the Pledgecom app, operated by Pledgecom Labs.
              </p>

              <p>
                <b>PERSONAL DATA</b> means data about a living individual who
                can be identified from that data (or from those and other
                information either in our possession or likely to come into our
                possession).
              </p>

              <p>
                <b>USAGE DATA</b> is data collected automatically either
                generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </p>

              <p>
                <b>COOKIES</b> are small files stored on your device (computer
                or mobile device).
              </p>

              <p>
                <b>DATA CONTROLLER</b> means a natural or legal person who
                (either alone or jointly or in common with other persons)
                determines the purposes for which and how any personal data are,
                or are to be, processed. For this Privacy Policy, we are a Data
                Controller of your data.
              </p>

              <p>
                <b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural
                or legal person who processes the data on behalf of the Data
                Controller. We may use the services of various Service Providers
                to process your data more effectively
              </p>

              <p>
                <b>DATA SUBJECT</b> is any living individual who is the subject
                of Personal Data.
              </p>

              <p>
                <b>THE USER</b> is the individual using our Service. The User
                corresponds to the Data Subject, who is the subject of Personal
                Data.
              </p>
            </li>

            <li>
              <b>Information Collection and Use</b>

              <p>
                We collect several different types of information for various
                purposes to provide and improve our Service to you.
              </p>
            </li>

            <li>
              <b>Types of Data Collected</b>

              <div className="sub-content">
                <h2>4.1. Personal Data</h2>
                <p>
                  While using our Service, we may ask you to provide us with
                  certain personally identifiable information that can be used
                  to contact or identify you (“Personal Data”). Personally
                  identifiable information may include, but is not limited to:
                </p>

                <ul className="list-disc ml-5 flex flex-col gap-2">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>
                    Address, Country, State, Province, ZIP/Postal code, City,
                  </li>
                  <li>Cookies and Usage Data</li>
                  <li>KYC Verification Photo</li>
                </ul>

                <p>
                  We may use your Data to contact you with newsletters and other
                  information that may be of interest to you. You may opt out of
                  receiving any, or all, of these communications from us by
                  following the unsubscribe link.
                </p>
              </div>

              <div className="sub-content">
                <h2>4.2. Usage Data</h2>

                <p>
                  We may also collect information that your browser sends
                  whenever you visit our Service or when you access the Service
                  by or through any device (“Usage Data”)
                </p>

                <p>
                  This Usage Data may include information such as your
                  computer’s Internet Protocol address (e.g. IP address),
                  browser type, browser version, the pages of our Service that
                  you visit, the time and date of your visit, the time spent on
                  those pages, unique device identifiers and other diagnostic
                  data
                </p>

                <p>
                  When you access Service with a device, this Usage Data may
                  include information such as the type of device you use, your
                  device unique ID, the IP address of your device, your device
                  operating system, the type of Internet browser you use, unique
                  device identifiers and other diagnostic data.
                </p>
              </div>

              <div className="sub-content">
                <h2>4.3. Location Data</h2>
                <p>
                  We may use and store information about your location if you
                  permit us to do so ("Location Data"). We use this data to
                  provide features of our Service and to improve and customize
                  our Service. You can enable or disable location services when
                  you use our Service at any time by way of your device
                  settings.
                </p>
              </div>

              <div className="sub-content">
                <h2>4.4. Tracking Cookies Data</h2>
                <p>
                  We use cookies and similar tracking technologies to track the
                  activity on our Service and we hold certain information
                </p>

                <p>
                  Cookies are files with a small amount of data which may
                  include an anonymous unique identifier. Cookies are sent to
                  your browser from a website and stored on your device. Other
                  tracking technologies are also used such as beacons, tags, and
                  scripts to collect and track information and to improve and
                  analyze our Service.
                </p>

                <p>
                  You can instruct your browser to refuse all cookies or to
                  indicate when a cookie is being sent. However, if you do not
                  accept cookies, you may not be able to use some portions of
                  our Service.
                </p>

                <p>Examples of Cookies we use:</p>

                <ul className="list-disc ml-5 flex flex-col gap-2">
                  <li>
                    <b>Session Cookies:</b> We use Session Cookies to operate
                    our Service
                  </li>

                  <li>
                    <b>Preference Cookies:</b> We use Preference Cookies to
                    remember your preferences and various settings.
                  </li>

                  <li>
                    <b>Security Cookies:</b> We use Security Cookies for
                    security purposes.
                  </li>
                </ul>
              </div>
            </li>

            <li>
              <b>Use of Data</b>

              <p>
                Pledgecom Labs uses the collected data for various purposes:
              </p>

              <ul className="list-disc ml-5 flex flex-col gap-2 mt-2">
                <li>To provide and maintain our Service.</li>
                <li>To perform KYC and authentication procedures.</li>
                <li>To notify you about changes to our Service</li>
                <li>
                  To allow you to participate in interactive features of our
                  Service when you choose to do so.
                </li>
                <li>To provide customer support.</li>
                <li>
                  To gather analysis or valuable information so that we can
                  improve our Service.
                </li>
                <li>To monitor the usage of our Service.</li>
                <li>To detect, prevent, and address technical issues.</li>
                <li>To fulfill any other purpose for which you provide it.</li>
                <li>
                  To carry out our obligations and enforce our rights arising
                  from any contracts entered into between you and us, including
                  for billing and collection.
                </li>
                <li>
                  To provide you with notices about your account and/or
                  subscription, including expiration and renewal notices, email
                  instructions, etc.
                </li>
                <li>
                  To provide you with news, special offers, and general
                  information about other goods, services, and events that we
                  offer that are similar to those that you have already
                  purchased or enquired about unless you have opted not to
                  receive such information.
                </li>
                <li>
                  In any other way, we may describe when you provide the
                  information.
                </li>
                <li>For any other purpose with your consent.</li>
              </ul>
            </li>

            <li>
              <b>Retention of Data</b>

              <p>
                We will retain your Data only for as long as is necessary for
                the purposes set out in this Privacy Policy. We will retain and
                use your Data to the extent necessary to comply with our legal
                obligations (for example, if we are required to retain your data
                to comply with applicable laws), resolve disputes, and enforce
                our legal agreements and policies.
              </p>

              <p>
                We will also retain Usage Data for internal analysis purposes.
                Usage Data is generally retained for a shorter period, except
                when this data is used to strengthen the security or to improve
                the functionality of our Service, or we are legally obligated to
                retain this data for longer periods.
              </p>
            </li>

            <li>
              <b>Transfer of Data</b>

              <p>
                Your information, including Personal Data, may be transferred to
                – and maintained on – computers located outside of your state,
                province, country, or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction
              </p>

              <p>
                Pledgecom Labs will take all the steps reasonably necessary to
                ensure that your data is treated securely and following this
                Privacy Policy and no transfer of your Personal Data will take
                place to an organization or a country unless there are adequate
                controls in place including the security of your data and other
                personal information.
              </p>
            </li>

            <li>
              <b>Disclosure of Data</b>

              <p>
                Pledgecom will not disclose personal information we hold to
                anyone. However, we will disclose this information in certain
                circumstances, such as:
              </p>

              <div className="sub-content">
                <h2>8.1. Disclosure for Law Enforcement</h2>
                <p>
                  Under certain circumstances, we may be required to disclose
                  your Data if required to do so by law or in response to valid
                  requests by public authorities
                </p>
              </div>

              <div className="sub-content">
                <h2>8.2. Business Transactions</h2>

                <p>
                  If we or our subsidiaries are involved in a merger,
                  acquisition, or asset sale, your Data may be transferred.
                </p>
              </div>

              <div className="sub-content">
                <h2>
                  8.3. Other cases. We may disclose your information also:
                </h2>

                <ul className="list-disc ml-5 flex flex-col gap-2">
                  <li>To our subsidiaries and affiliates</li>
                  <li>To fulfill the purpose for which you provide it, and</li>
                  <li>With your consent in any other cases</li>
                </ul>
              </div>
            </li>

            <li>
              <b>Security of Data</b>

              <p>
                The security of your data is important to us but remember that
                no method of transmission over the Internet or method of
                electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your Personal Data, we
                cannot guarantee its absolute security.
              </p>
            </li>

            <li>
              <b>
                Your Data Protection Rights Under the General Data Protection
                Regulation (GDPR)
              </b>

              <p>
                If you are a resident of the European Union (EU) and European
                Economic Area (EEA), you have certain data protection rights,
                covered by GDPR.
              </p>

              <p>
                We aim to take reasonable steps to allow you to correct, amend,
                delete, or limit the use of your Personal Data.
              </p>

              <p>
                If you wish to be informed what Personal Data we hold about you
                and if you want it to be removed from our systems, please email
                us at
                <a href="mailto:support@pledgecom.org">support@pledgecom.org</a>
              </p>

              <p>
                In certain circumstances, you have the following data protection
                rights:
              </p>

              <div className="sub-content">
                <p>
                  10.1. The right to access, update, or delete the information
                  we have on you.
                </p>

                <p>
                  10.2. The right of rectification. You have the right to have
                  your information rectified if that information is inaccurate
                  or incomplete.
                </p>

                <p>
                  10.3. The right to object. You have the right to object to our
                  processing of your Personal Data.
                </p>

                <p>
                  10.4. The right of restriction. You have the right to request
                  that we restrict the processing of your personal information.
                </p>

                <p>
                  10.5. The right to data portability. You have the right to be
                  provided with a copy of your Personal Data in a structured,
                  machine-readable, and commonly used format
                </p>

                <p>
                  10.6. The right to withdraw consent. You also have the right
                  to withdraw your consent at any time when we rely on your
                  consent to process your personal information
                </p>
              </div>

              <p>
                Please note that we may ask you to verify your identity before
                responding to such requests. Also, note that we may not be able
                to provide Service without some necessary data
              </p>

              <p>
                You have the right to complain to a Data Protection Authority
                about our collection and use of your Personal Data. For more
                information, please contact your local data protection authority
                in the European Economic Area (EEA).
              </p>
            </li>

            <li>
              <b>
                Your Data Protection Rights under the California Privacy
                Protection Act (CalOPPA)
              </b>

              <p>
                CalOPPA is the first state law in the nation to require
                commercial websites and online services to post a privacy
                policy. The law’s reach stretches well beyond California to
                require a person or company in the United States (and
                conceivably, the world) that operates websites collecting
                personally identifiable information from California consumers to
                post a conspicuous privacy policy on its website stating exactly
                the information being collected and those individuals with whom
                it is being shared and to comply with this policy.
              </p>

              <p>According to CalOPPA, we agree to the following:</p>

              <div className="sub-content">
                <p>11.1 Users can visit our site anonymously.</p>
                <p>
                  11.2 Our Privacy Policy link includes the word “Privacy”, and
                  can easily be found on the home page of our website.
                </p>
                <p>
                  11.3 Users will be notified of any privacy policy changes on
                  our Privacy Policy Page.
                </p>
                <p>
                  11.4 Users can change their personal information by emailing
                  us at
                  <a href="mailto:support@pledgecom.org">
                    support@pledgecom.org
                  </a>
                  .
                </p>
              </div>

              <h3 className="text-2xl font-bold mt-7">
                Our Policy on "Do Not Track" Signals:
              </h3>

              <p>
                We honor Do Not Track signals and do not track plant cookies. Do
                Not Track is a preference you can set in your web browser to
                inform websites that you do not want to be tracked. You can
                enable or disable Do Not Track by visiting the Preferences or
                Settings page of your web browser
              </p>
            </li>

            <li>
              <b>
                Your Data Protection Rights under the California Consumer
                Privacy Act (CCPA)
              </b>

              <p>
                If you are a California resident, you are entitled to learn what
                data we collect about you, ask to delete your data, and not to
                sell (share) it. To exercise your data protection rights, you
                can make certain requests and ask us:
              </p>

              <div className="sub-content">
                <p>
                  12.1. The personal information we have about you. If you make
                  this request, we will return to you
                </p>

                <ul className="ml-5 flex flex-col gap-2 pl-3">
                  <li>
                    12.1.1. The categories of personal information we have
                    collected about you.
                  </li>

                  <li>
                    12.1.2. The categories of sources from which we collect your
                    personal information.
                  </li>

                  <li>
                    12.1.3. The business or commercial purpose for collecting or
                    selling your personal information.
                  </li>
                </ul>

                <p>
                  Please note that you are entitled to ask us to provide you
                  with this information up to two times in a rolling
                  twelve-month period. When you make this request, the
                  information provided may be limited to the personal
                  information we collected about you in the previous 12 months.
                </p>

                <p>
                  12.2. If you choose to delete your personal information, you
                  can do so by deleting your account from the Pledgecom app.
                  Once you have deleted your account you will no longer be able
                  to access the Pledgecom app.
                </p>

                <p>
                  12.3. Stop selling your personal information. We don’t sell or
                  rent your personal information to any third parties for any
                  purpose. We do not sell your personal information for monetary
                  consideration. However, under some circumstances, a transfer
                  of personal information to a third party, or within our family
                  of companies, without monetary consideration may be considered
                  a “sale” under California law. You are the only owner of your
                  Personal Data and can request disclosure or deletion at any
                  time.
                </p>
              </div>

              <p>
                If you submit a request to stop selling your personal
                information, we will stop making such transfers.
              </p>

              <p>
                Please note that if you ask us to delete or stop selling your
                data, it may impact your experience with us, and you may not be
                able to participate in certain programs or membership services
                that require the usage of your personal information to function.
                But in no circumstances, we will discriminate against you for
                exercising your rights.
              </p>

              <p>
                To exercise your California data protection rights described
                above, please send your request(s) by email:
                <a href="mailto:support@pledgecom.org">support@pledgecom.org</a>
                .
              </p>

              <p>
                Your data protection rights, described above, are covered by the
                CCPA, short for the California Consumer Privacy Act. To find out
                more, visit the official California Legislative Information
                website. The CCPA took effect on 01/01/2020.
              </p>
            </li>

            <li>
              <b>Service Providers</b>

              <p>
                We may employ third-party companies and individuals to
                facilitate our Service (“Service Providers”), provide Service on
                our behalf, perform Service-related services, or assist us in
                analyzing how our Service is used. These third parties could
                have access to your Personal Data only to perform these tasks on
                our behalf and are obligated not to disclose or use it for any
                other purpose.
              </p>
            </li>

            <li>
              <b>Analytics</b>

              <p>
                We may use third-party Service Providers to monitor and analyze
                the use of our Service.
              </p>
            </li>

            <li>
              <b>CI/CD tools</b>

              <p>
                We may use third-party Service Providers to automate the
                development process of our Service.
              </p>
            </li>

            <li>
              <b>Behavioural Remarketing</b>
              <p>
                We may use remarketing services to advertise on third-party
                websites to you after you visit our Service. We and our
                third-party vendors use cookies to inform, optimize, and serve
                ads based on your past visits to our Service.
              </p>
            </li>

            <li>
              <b>links to Other sites</b>
              <p>
                Our Service may contain links to other sites that are not
                operated by us. If you click a third-party link, you will be
                directed to that third-party’s site. We strongly advise you to
                review the Privacy Policy of every site you visit.
              </p>

              <p>
                We have no control over and assume no responsibility for the
                content, privacy policies, or practices of any third-party sites
                or services.
              </p>
            </li>

            <li>
              <b>Children's Privacy</b>

              <p>
                Our Services are not intended for use by children under the age
                of 16 (<b>"Child"</b> or <b>"Children"</b>). We do not knowingly
                collect personally identifiable information from children under
                16. If you become aware that a Child has provided us with
                Personal Data, please contact us. If we become aware that we
                have collected Personal Data from Children without verification
                of parental consent, we take steps to remove that information
                from our servers.
              </p>
            </li>

            <li>
              <b>Changes to This Privacy Policy</b>

              <p>
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page. <br />
                <br />
                We will let you know via email and/or a prominent notice on our
                Service, before the change becomes effective and update the
                “effective date” at the top of this Privacy Policy.
                <br />
                <br />
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
            </li>

            <li>
              <b>Contact us</b>
              <p>
                If you have any questions about this Privacy Policy, please
                contact us by email:
                <a href="mailto:support@pledgecom.org">support@pledgecom.org</a>
                .
              </p>
            </li>
          </ul>

          <p className="italic font-semibold text-xl text-center mt-4">
            This privacy policy was last updated on 23<sup>rd</sup> June 2024.
          </p>
        </div>
      </div>
    </section>
  );
}
